Fix NoSuchMethodError when calling FbReactApplicationBaseSonarUtil.startSonarClient
Summary:
This diff is fixing a NoSuchMethodError when calling FbReactApplicationBaseSonarUtil.startSonarClient.

This is causing catalyst Android app to not start.

This was caused by D47468613, which changed the signature of the method

Reviewed By: cortinico

Differential Revision: D48275730

fbshipit-source-id: 4693c299dbd3b6a9ad58a1439bddd9e4bfb8bdf5