Handle RSocket disconnects gracefully
Summary:
Tiny change, hours of debugging. Big thanks to jknoxville for
answering all my stupid questions.

Our number one "error" right now by users affected is

```
Unhandled Promise Rejection:
Error: RSocketTcpClient:
Socket closed unexpectedly.
```

Of course no stacktrace, because JavaScript and Promises.

The underlying problem is that RSocket keeps track of recently used
"receivers" which is every method that has sent a request. When someone disconnects their device or closes an emulator/simulator, the socket's `end` event is treated the same way any other connection error would be: https://github.com/rsocket/rsocket-js/blob/a85a4db0417717a8734b594e24de9c374eca2851/packages/rsocket-tcp-client/src/RSocketTcpClient.js#L74

This then causes "errors" like these to appear:
{F609810187}

This could previously be handled in plugin-code by wrapping all `client.call()` invocations in try/catch, which nobody did, meaning we'd get rejected promises everywhere. We can instead handle this centrally and properly disconnect the connection.

Changelog: Severed RSocket connections are no longer treated as an error in plugin code

Reviewed By: jknoxville

Differential Revision: D27910514

fbshipit-source-id: ea9c0726ab0e959b0eb4a5fca67ddaa04a6f1d14