Fix for compilation error about missing virtual destructor in GCDQueue (#236)
Summary:
error: destructor called on non-final 'facebook::sonar::GCDQueue' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
    __data_.second().~_Tp();
Pull Request resolved: https://github.com/facebook/flipper/pull/236

Reviewed By: passy

Differential Revision: D9351946

Pulled By: priteshrnandgaonkar

fbshipit-source-id: 4718460ff587e1d5fa475a5f3bf115b1e2b5305f