Remove condition empty or null name in SharedPreferencesFlipperPlugin (#5480)
Summary:
If someone creates preferences with an empty name, the application will crash when the plugin is initialized:
```kotlin
context.getSharedPreferences("", Context.MODE_PRIVATE).edit()
   .putString("test", "test")
   .commit()
```

The crash:
```java
FATAL EXCEPTION: main
Process: ru.mail.mailapp, PID: 23504
java.lang.RuntimeException: Unable to create application ru.mail.MailApplication: java.lang.IllegalArgumentException: Given null or empty name
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7690)
    at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8893)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.IllegalArgumentException: Given null or empty name
    at com.facebook.flipper.plugins.sharedpreferences.SharedPreferencesFlipperPlugin$SharedPreferencesDescriptor.<init>(SharedPreferencesFlipperPlugin.java:268)
    at com.facebook.flipper.plugins.sharedpreferences.SharedPreferencesFlipperPlugin.buildDescriptorForAllPrefsFiles(SharedPreferencesFlipperPlugin.java:131)
    at com.facebook.flipper.plugins.sharedpreferences.SharedPreferencesFlipperPlugin.<init>(SharedPreferencesFlipperPlugin.java:66)

```

## Changelog

Removing a check for an empty preference name

Pull Request resolved: https://github.com/facebook/flipper/pull/5480

Test Plan:
```kotlin
// Add this code before init plugin
context.getSharedPreferences("", Context.MODE_PRIVATE).edit()
                    .putString("test", "test")
                    .commit()
// Init plugin
client.addPlugin(SharedPreferencesFlipperPlugin(context))
```

Reviewed By: mweststrate

Differential Revision: D54416921

Pulled By: passy

fbshipit-source-id: 52ef807bb3b011f20d62f71d4f969dc7439f40ce