Fix removeX callsites (4/N)
Summary: Because of a Kotlin bug with JDK21 when using SDK 35, removeFirst() and removeLast() cause a runtime `NoSuchMethodError` when called with a MutableList, List or ArrayList. So fixing these callsites before the SDK 35 upgrade

Reviewed By: jselbo

Differential Revision: D59592734

fbshipit-source-id: 33c5a253917143c59ee9315f2f1a60c4fd88ea60