Fix for compilation error about missing virtual destructor in GCDQueue
error: destructor called on non-final 'facebook::sonar::GCDQueue' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
    __data_.second().~_Tp();