Bump org.jetbrains.dokka:dokka-gradle-plugin from 1.7.20 to 1.8.10 (#4590)
Summary:
Bumps [org.jetbrains.dokka:dokka-gradle-plugin](https://github.com/Kotlin/dokka) from 1.7.20 to 1.8.10.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/Kotlin/dokka/releases">org.jetbrains.dokka:dokka-gradle-plugin's releases</a>.</em></p>
<blockquote>
<h2>1.8.10 Beta</h2>
<p>Dokka's documentation has been entirely rewritten and can now be found on <a href="https://kotlinlang.org/docs/dokka-introduction.html">kotlinlang.org</a>:</p>
<ul>
<li>More examples, including Groovy DSL for Gradle project configuration</li>
<li>More guidelines to help beginners</li>
<li>More details for complex projects</li>
</ul>
<p><strong>Note</strong>: Version 1.8.0 was skipped due to a Metaspace memory leak in Kotlin's reflection (<a href="https://youtrack.jetbrains.com/issue/KT-56093">KT-56093</a>). Dokka 1.8.10 should be fully compatible with Kotlin 1.8.0.</p>
<h2>Improvements</h2>
<ul>
<li>Revise project documentation and examples (<a href="https://redirect.github.com/Kotlin/dokka/issues/2728">https://github.com/facebook/flipper/issues/2728</a>, <a href="https://redirect.github.com/Kotlin/dokka/issues/2737">https://github.com/facebook/flipper/issues/2737</a>, <a href="https://redirect.github.com/Kotlin/dokka/issues/2736">https://github.com/facebook/flipper/issues/2736</a>). Thanks to <a href="https://github.com/sarahhaggarty"><code>@​sarahhaggarty</code></a> for helping!</li>
<li>Support generating documentation for Kotlin/Wasm projects (<a href="https://redirect.github.com/Kotlin/dokka/issues/2814">#2814</a>). Thanks to <a href="https://github.com/igoriakovlev"><code>@​igoriakovlev</code></a>!</li>
<li>Move the contents of <code>Inheritors</code>, <code>Parameters</code>, <code>See also</code> and <code>Samples</code> tabs into the main declaration description (<a href="https://redirect.github.com/Kotlin/dokka/issues/2688">https://github.com/facebook/flipper/issues/2688</a>).</li>
<li>Add <code>Members</code> and <code>Members &amp; Extensions</code> tabs to class-like declaration pages (<a href="https://redirect.github.com/Kotlin/dokka/issues/2764">https://github.com/facebook/flipper/issues/2764</a>).</li>
<li>Display source set / platform indicators at all times, which should help identify the supported platform of single-platform libraries and modules. (<a href="https://redirect.github.com/Kotlin/dokka/issues/2847">https://github.com/facebook/flipper/issues/2847</a>).</li>
<li>Generate the default no-arg constructor for Java declarations (<a href="https://redirect.github.com/Kotlin/dokka/issues/2765">https://github.com/facebook/flipper/issues/2765</a>).</li>
</ul>
<h2>Bugfixes</h2>
<ul>
<li>Fixed analysis environment not being properly disposed (<a href="https://redirect.github.com/Kotlin/dokka/issues/2755">https://github.com/facebook/flipper/issues/2755</a>).</li>
<li>Fixed nondeterministic sorting of function/property overloads (<a href="https://redirect.github.com/Kotlin/dokka/issues/2784">https://github.com/facebook/flipper/issues/2784</a>).</li>
<li>Fixed inconsistent alphabetical order of element groups in index and navigation (<a href="https://redirect.github.com/Kotlin/dokka/issues/2861">https://github.com/facebook/flipper/issues/2861</a>).</li>
<li>Fixed constructors being rendered as functions (<a href="https://redirect.github.com/Kotlin/dokka/issues/2689">https://github.com/facebook/flipper/issues/2689</a>).</li>
<li>Fixed default values for <code>var</code> properties being displayed (<a href="https://redirect.github.com/Kotlin/dokka/issues/2717">https://github.com/facebook/flipper/issues/2717</a>).</li>
<li>Fixed source links leading to the KDoc instead of the declaration (<a href="https://redirect.github.com/Kotlin/dokka/issues/2724">https://github.com/facebook/flipper/issues/2724</a>).</li>
<li>Fixed thread-safety issues in <code>DokkaLogger</code> (<a href="https://redirect.github.com/Kotlin/dokka/issues/2827">#2827</a>).</li>
<li>Fixed documentation not being inherited in case of diamond inheritance (<a href="https://redirect.github.com/Kotlin/dokka/issues/2686">https://github.com/facebook/flipper/issues/2686</a>).</li>
</ul>
<h3>Gradle Plugin</h3>
<ul>
<li>Fixed <code>NoSuchMethodError</code> when running under Gradle 8 (<a href="https://redirect.github.com/Kotlin/dokka/issues/2796">#2796</a>).</li>
<li>Fixed possible metaspace leaks due to external thread locals not being disposed (<a href="https://redirect.github.com/Kotlin/dokka/issues/2678">https://github.com/facebook/flipper/issues/2678</a>).</li>
<li>Fixed premature initialization of <code>outputDirectory</code> input property (<a href="https://redirect.github.com/Kotlin/dokka/issues/556">https://github.com/facebook/flipper/issues/556</a>).</li>
<li>Fixed premature initialization of <code>moduleVersion</code> input property (<a href="https://redirect.github.com/Kotlin/dokka/issues/2799">#2799</a>). Thanks to <a href="https://github.com/JavierSegoviaCordoba"><code>@​JavierSegoviaCordoba</code></a>!</li>
<li>Fixed unnecessary snapshotting of source link directory input which led to performance problems (<a href="https://redirect.github.com/Kotlin/dokka/issues/2807">#2807</a>).</li>
<li>Fixed missing group and description for <code>MultiModule</code> tasks (<a href="https://redirect.github.com/Kotlin/dokka/issues/2806">#2806</a>). Thanks to <a href="https://github.com/TWiStErRob"><code>@​TWiStErRob</code></a>!</li>
</ul>
<h3>Javadoc</h3>
<ul>
<li>Fixed truncation of module and package description after the first sentence (<a href="https://redirect.github.com/Kotlin/dokka/issues/2055">https://github.com/facebook/flipper/issues/2055</a>). Thanks to <a href="https://github.com/BlackAnubis7"><code>@​BlackAnubis7</code></a>!</li>
<li>Fixed rendering of empty/useless Kotlin companion objects (<a href="https://redirect.github.com/Kotlin/dokka/issues/200">https://github.com/facebook/flipper/issues/200</a>, <a href="https://redirect.github.com/Kotlin/dokka/issues/2086">https://github.com/facebook/flipper/issues/2086</a>)</li>
<li>Fixed leaking configuration/environment details in generated links (<a href="https://redirect.github.com/Kotlin/dokka/issues/2803">#2803</a>).</li>
<li>Fixed incorrect links when <code>javadoc.jar</code> produced by Dokka is imported into IntelliJ IDEA / Android Studio (<a href="https://redirect.github.com/Kotlin/dokka/issues/2734">https://github.com/facebook/flipper/issues/2734</a>). Thanks to <a href="https://github.com/bomberaya"><code>@​bomberaya</code></a>!</li>
</ul>
<h2>Plugin API</h2>
<ul>
<li>Mark Plugin API as experimental (<a href="https://redirect.github.com/Kotlin/dokka/issues/2716">https://github.com/facebook/flipper/issues/2716</a>).</li>
</ul>
<h2>Infrastructure</h2>

</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/Kotlin/dokka/commit/775377625994339aff47b078013f60f518d22919"><code>7753776</code></a> Do no render Types tab when there are no types (<a href="https://redirect.github.com/Kotlin/dokka/issues/2900">https://github.com/facebook/flipper/issues/2900</a>)</li>
<li><a href="https://github.com/Kotlin/dokka/commit/4b5a88dd92247f40c274d24ca5c0112d81a51d2c"><code>4b5a88d</code></a> Do not propagate opt-in</li>
<li><a href="https://github.com/Kotlin/dokka/commit/aba2d129755f5a982def77d8e7d0e741fd29b84a"><code>aba2d12</code></a> Update dokka_version to the release one</li>
<li><a href="https://github.com/Kotlin/dokka/commit/5ccda6f19e2200160bc6bd6cc2ed8df9dca48117"><code>5ccda6f</code></a> Mark Plugin Api as experimental (<a href="https://redirect.github.com/Kotlin/dokka/issues/2743">https://github.com/facebook/flipper/issues/2743</a>)</li>
<li><a href="https://github.com/Kotlin/dokka/commit/605ce9ee6ba096dc206784e3c2ab1ea3680e2980"><code>605ce9e</code></a> Reorganize tabs for Classlike (<a href="https://redirect.github.com/Kotlin/dokka/issues/2764">https://github.com/facebook/flipper/issues/2764</a>)</li>
<li><a href="https://github.com/Kotlin/dokka/commit/57622719edb912d7c3320f7e59cd6928e5c25e44"><code>5762271</code></a> Exclude user guides from mkdocs documentation (<a href="https://redirect.github.com/Kotlin/dokka/issues/2868">https://github.com/facebook/flipper/issues/2868</a>)</li>
<li><a href="https://github.com/Kotlin/dokka/commit/1e10c6f47d605e1e730cb58aa44f3051ec5a493b"><code>1e10c6f</code></a> Fix mkdocs documentation leading to non-stable versions (<a href="https://redirect.github.com/Kotlin/dokka/issues/2870">https://github.com/facebook/flipper/issues/2870</a>)</li>
<li><a href="https://github.com/Kotlin/dokka/commit/1fd045904e94d68878b3a5f748bf20f7c61a1cf7"><code>1fd0459</code></a> Consistent alphabetical order of element groups in index and navigation (<a href="https://redirect.github.com/Kotlin/dokka/issues/2861">https://github.com/facebook/flipper/issues/2861</a>)</li>
<li><a href="https://github.com/Kotlin/dokka/commit/daed35f92b3b482688856d139da6849c8e6b4ab1"><code>daed35f</code></a> Do not render filter-section for empty source sets (<a href="https://redirect.github.com/Kotlin/dokka/issues/2858">https://github.com/facebook/flipper/issues/2858</a>)</li>
<li><a href="https://github.com/Kotlin/dokka/commit/e8423ecf9f430758398eabc0d35077fff17f1f6c"><code>e8423ec</code></a> Deprecate methods for adding/removing task dependencies (<a href="https://redirect.github.com/Kotlin/dokka/issues/2857">https://github.com/facebook/flipper/issues/2857</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/Kotlin/dokka/compare/v1.7.20...v1.8.10">compare view</a></li>
</ul>
</details>
<br />

[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.jetbrains.dokka:dokka-gradle-plugin&package-manager=gradle&previous-version=1.7.20&new-version=1.8.10)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

 ---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `dependabot rebase` will rebase this PR
- `dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `dependabot merge` will merge this PR after your CI passes on it
- `dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `dependabot cancel merge` will cancel a previously requested merge and block automerging
- `dependabot reopen` will reopen this PR if it is closed
- `dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)

</details>

Pull Request resolved: https://github.com/facebook/flipper/pull/4590

Reviewed By: ivanmisuno

Differential Revision: D44215161

Pulled By: mweststrate

fbshipit-source-id: 527b8289a40e19d2128abe61e6097d7401616b78